### ISSUE TITLE
ubuntu12.04LTS+ texlive-full2009 下编译不通过

### ISSUE THREAD

**Issue by zhangl** [Haixing-Hu/nju-thesis#12]
一个是默认的英文字体没有。。
\newcommand_{\njut@enfn@main}{Times}
\newcommand_{\njut@enfn@sans}{Helvetica}
\newcommand_{\njut@enfn@mono}{Courier}
改成下面后通过
\newcommand_{\njut@enfn@main}{Times New Roman}
\newcommand_{\njut@enfn@sans}{Arial}
\newcommand_{\njut@enfn@mono}{Courier New}

但又有新的问题
Package blindtext Warning: pinyin not defined, using English instead.
(blindtext)                 on input line 164.

! Package babel Error: You haven't loaded the option english yet.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.164 \englishkeywords
                      {Small World, Network Model, Data Center}

**Comment by Haixing-Hu** [comment]
关于第一个问题，我不太清楚现在ubuntu linux上安装的标准的英文字体是什么。Times New Roman好像是Windows自带的微软字体呀，而且是有版权的。是不是需要安装个字体包，才能有Times字体？试试看安装 xfonts-* 之类的字体包。

关于第二个问题，按理说不该有问题的，不知道啥原因 ;-(

**Comment by Haixing-Hu** [comment]
不再支持TexLive2009，至少要使用 TexLive 2012版本。
