### ISSUE TITLE
The package isn't compatible with the latest texlive

### ISSUE THREAD

**Issue by clouds56** [Haixing-Hu/nju-thesis#15]
`make sample` shows:(with linuxfonts,phd)

> Underfull \vbox (badness 10000) has occurred while \output is active [3]
> Underfull \hbox (badness 4752) in paragraph at lines 332--333
> []|\EU1/AdobeSongStd(0)/m/n/12.05 距 离 \EU1/DejaVuSerif(0)/m/n/12.05 GMT \EU1/Ad
> obeSongStd(0)/m/n/12.05 时 间
> ! TeX capacity exceeded, sorry [input stack size=5000].
> \reserved@a ->\def \reserved@a 
>                                _{\caption@startrue \caption@dblarg {\@captio...
> l.338   \caption{
>                  测试表格}\label{table:test1}
> Output written on sample.pdf (23 pages).
> Transcript written on sample.log.
> Makefile:55: recipe for target 'sample.pdf' failed
> make: *_\* [sample.pdf] Error 1

the `xelatex -v` shows

> XeTeX 3.14159265-2.6-0.99991 (TeX Live 2014/Arch Linux)
> kpathsea version 6.2.0
> Copyright 2014 SIL International, Jonathan Kew and Khaled Hosny.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the XeTeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the XeTeX source.
> Primary author of XeTeX: Jonathan Kew.
> Compiled with ICU version 55.1; using 55.1
> Compiled with zlib version 1.2.8; using 1.2.8
> Compiled with FreeType2 version 2.5.5; using 2.5.5
> Compiled with Graphite2 version 1.2.4; using 1.2.4
> Compiled with HarfBuzz version 0.9.40; using 0.9.40
> Compiled with libpng version 1.6.16; using 1.6.16
> Compiled with poppler version 0.32.0
> Compiled with fontconfig version 2.11.1; using 2.11.1

the texlive-core version

> Name           : texlive-core
> Version        : 2014.36709-1
> Description    : TeX Live core distribution
> Architecture   : any
> URL            : http://tug.org/texlive/
> Licenses       : GPL
> Groups         : texlive-most
> Provides       : tetex  texlive-latex3
> Depends On     : texlive-bin  perl
> Optional Deps  : dialog: for texconfig [installed]
>                  ghostscript: for epstopdf, epspdf and other ConTeXt tools [installed]
>                  java-runtime: for utilities like arara
>                  perl-tk: for texdoctk
>                  psutils: to manipulate the output of dvips
>                  python: for pythontex [installed]
>                  python2: for dviasm [installed]
>                  ruby: for old ConTeXT MkII and epspdf [installed]
>                  t1utils: can be useful when installing Type1 fonts
> Required By    : texlive-bibtexextra  texlive-fontsextra  texlive-formatsextra  texlive-games  texlive-genericextra  texlive-htmlxml  texlive-humanities  texlive-langchinese
>                  texlive-langjapanese  texlive-langkorean  texlive-latexextra  texlive-music  texlive-pictures  texlive-plainextra  texlive-pstricks  texlive-publishers
>                  texlive-science  texvc
> Optional For   : ghostscript
> Conflicts With : tetex  texlive-latex3
> Replaces       : tetex  texlive-latex3
> Installed Size : 297.67 MiB
> Packager       : Rémy Oudompheng remy@archlinux.org
> Build Date     : Mon 06 Apr 2015 06:40:51 AM CST
> Install Date   : Sun 12 Apr 2015 01:54:13 PM CST
> Install Reason : Explicitly installed
> Install Script : Yes
> Validated By   : Signature

**Comment by imchenxi** [comment]
Same issue here:

> ! TeX capacity exceeded, sorry [input stack size=5000].

**Comment by Haixing-Hu** [comment]
这个问题看上去是Tex Live升级带来的问题。由于我一直使用Tex Live 2012，一直没发现问题。but, 我最近升级到tex live 2014，编译时也没有问题呀。

我现在无法重现上述问题，各位可以试试看改用Tex Live 2014，安装时完整安装。

**Comment by imchenxi** [comment]
升到Tex Live 2015后不会出现“stack size”的问题了：）

**Comment by Haixing-Hu** [comment]
太好了，看来是某些包的兼容性问题

Xi Chen wrote:

**Comment by imchenxi** [comment]
提交了一个pull request，可以实现高版本中修改下划线颜色了：https://github.com/Haixing-Hu/nju-thesis/pull/17

**Comment by Haixing-Hu** [comment]
已支持TexLive 2015
