### ISSUE TITLE
正文字体是不是大了？

### ISSUE THREAD

**Issue by xiedingbao** [Haixing-Hu/nju-thesis#18]
我在mac下编译，由于我已经将windows里的字体都拷贝过来了，所以在cls文件里，直接使用了windows
字体。我手上有已毕业师兄的博士论文，我数了一下，他们的正文一行大概有37个字，而这个模板大概只有31个。请问，这个模板的字体大小符合学校要求吗？

**Comment by Haixing-Hu** [comment]
完全符合国家规范和学校要求。

所遵循的南京大学研究生院的要求如下：

- [南京大学硕士答辩流程及相关材料](http://gs.nju.edu.cn/content/xw/ss3.htm)
- [南京大学博士答辩流程及相关材料](http://gs.nju.edu.cn/content/xw/bs3.htm)
- [南京大学博士(硕士)学位论文编写格式规定(试行)](http://grawww.nju.edu.cn/content/xw/lwgf.doc)

所遵循的中华人民共和国国家标准如下：

- GB/T 7714-2005 文后参考文献著录规则
- GB/T 7713.1-2006 学位论文编写规则
- GB/T 7713.3-2009 科技报告编写规则
- GB/T 7713-1987 科学技术报告、学位论文和学术论文的编写格式(该标准已被 GB/T 7713.1-2006 和 GB/T 7713.3-2009 部分替代)
- GB/T 7156-2003 文献保密等级代码与标识
- GB/T 16159-2012 汉语拼音正词法基本规则(该标准取代了 GB/T 16159-1996)
- CY/T 35-2001 科技文献的章节编号方法

**Comment by Haixing-Hu** [comment]
补充一下，关于字体的要求：正文使用小四号字体(折算为12.05pt，近似使用了12pt)，行间距为固定值20pt。纸张使用A4，双面打印。页眉：2.6cm，页脚：2.4cm，页边距上下：3.5cm，左右：3.2cm
