### ISSUE TITLE
封面如何使用一行的标题？\title{} 好像不起作用

### ISSUE THREAD

**Issue by yangfeit19** [Haixing-Hu/nju-thesis#20]
\title{} 中的标题不显示在封面上。
\titlea{}和\titleb{}可以

**Comment by fxlnjfu** [comment]
是啊,这显然是一个bug.默认的标题就是两行的,一行的不行,但是不知道该怎么改?

**Comment by njuliujl** [comment]
_njuthesis.cls_
865行改为
`      \ifdefempty{\njut@cap@cover@title}{\njut@covertable@twolinetitle}{\njut@covertable@onelinetitle}
`

**Comment by Haixing-Hu** [comment]
直接把`\titlea{}`设置为完整的标题，`\titleb{}`空着即可

**Comment by Haixing-Hu** [comment]
另外，如果`titlea`, `titleb`不做定义，那么默认`\titlea`会使用`\title`设置的值，`\titleb`会设置为空。
参见`sample.tex`中的代码。
