### ISSUE TITLE
xelatex下可以使用公式的preview吗？

### ISSUE THREAD

**Issue by kirchhoff** [Haixing-Hu/nju-thesis#21]
我对选定公式进行 C-c C-p C-r 的时候，报错，我看auctex使用的是这条命令：
Running `Preview-LaTeX' on`_region_' with ``pdflatex -file-line-error -shell-escape --synctex=1 "\nonstopmode\nofiles\PassOptionsToPackage{active,tightpage,auctex}{preview}\AtBeginDocument{\ifx\ifPreview\undefined\RequirePackage[displaymath,floats,graphics,textmath,sections,footnotes]{preview}[2004/11/05]\fi}" "\input" _region_.tex''

**Comment by Haixing-Hu** [comment]
不要用公式preview，这个问题会比较多。
如果对公式没把握，找个在线的latex公式编辑器用用，可以所见即所得地预览公式。确认了后再复制代码到文档中。
