### ISSUE TITLE
longtitle-sample.tex 文件在ctex下可以xelatex编译通过，但不生产pdf文件，是缺少字体库吧？这种问题怎么修改，不知道哪种库

### ISSUE THREAD

**Issue by NieYongming** [Haixing-Hu/nju-thesis#22]
longtitle-sample.tex 文件在ctex下可以xelatex编译通过，但不生产pdf文件，是缺少字体库吧？这种问题怎么修改，不知道哪种库

**Comment by Haixing-Hu** [comment]
最新版ctex似乎缺少相应的字体，好像是将原来包含的adobe字体去掉了。你需要自己安装adobe字体，或者在windows下面，文档参数设置为 `winfonts`，如下所示：
```
\documentclass[winfonts]{njuthesis}
```
