### ISSUE TITLE
如何去除多余的空白页？

### ISSUE THREAD

**Issue by fxlnjfu** [Haixing-Hu/nju-thesis#24]
如题，每一个章节，摘要后都有一个空白页，这显然不合理啊，
有人知道怎么改吗？

**Comment by Haixing-Hu** [comment]
这不是空白页，而是双面打印的要求。因为是双面打印，因此摘要页背面是空白。
A4纸双面打印是南京大学研究生院对硕士博士论文的排版要求之一。
