### ISSUE TITLE
请问如何将目录中的章目录变成第一章。。。第二章这样的形式

### ISSUE THREAD

**Issue by dreamsuifeng** [Haixing-Hu/nju-thesis#29]
![image](https://user-images.githubusercontent.com/5406209/39540536-7e17eea0-4e75-11e8-8846-9fb675b424a0.png)
变成
![image](https://user-images.githubusercontent.com/5406209/39540559-8f26432c-4e75-11e8-95c3-3bd58988b105.png)

**Comment by dreamsuifeng** [comment]
最近找到了解决办法。
step1.
\usepackage{titlesec}  
\usepackage{titletoc}
\titlecontents{chapter}[0pt]{\addvspace{1.5pt}\filright\bf}%
               {\contentspush{第 \thecontentslabel\  章 \quad}}%
               {}{\titlerule*[8pt]{.}\contentspage}

在论文导引去加上上述命令，目录会变成“第1章”这样的形式，

step2.
在你的"**.toc"文件中把每章节前面的序号手动改成大写的序号
![image](https://user-images.githubusercontent.com/5406209/40058818-e8dee4b4-5884-11e8-843d-1751a54eddec.png)
变成如下图所示
![image](https://user-images.githubusercontent.com/5406209/40058832-f67739be-5884-11e8-8b00-bf3fed400983.png)
然后重新编译就可以了。

Note:
**.toc文件每次会重新生成，所以章节目录最好最后在修改。

**Comment by hitvoice** [comment]
我写了个自动改目录的脚本...就不用每次手改了（仅限于9章以内的论文），希望对大家有帮助。

```python
import re

toc_file = 'thesis.toc'
regex = re.compile(r'(?<={chapter}{\\numberline {)\d+')


def replace(m):
    s = m.group()
    mapper = {i: c for i, c in zip('123456789', '一二三四五六七八九')}
    if s not in mapper:
        raise NotImplementedError(f'{s} unknown or out of range!')
    return mapper[s]


if __name__ == "__main__":
    with open(toc_file) as f:
        lines = f.readlines()

    with open(toc_file, 'w') as f:
        for line in lines:
            f.write(regex.sub(replace, line))
```
以上代码保存为`fix_toc.py`，编译的命令就变成（以文件名为thesis为例）：
```sh
xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf thesis
bibtex thesis
xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf thesis
python3 fix_toc.py
xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf thesis
```
这样就可以每次通过脚本自动编译啦！👏

**Comment by njuhan** [comment]
如果没有附录(附录的编号大于10，并且用字母AB...表示)，直接添加以下代码即可
```
\usepackage{titlesec}
\usepackage{titletoc}
\titlecontents{chapter}[0pt]{\addvspace{1.5pt}\filright\bf}%
{\contentspush{第 \CJKnumber{\thecontentslabel}\ 章 \ \ }}%
{}{\titlerule*[8pt]{.}\contentspage}
```
