### ISSUE TITLE
章节序号丢失

### ISSUE THREAD

**Issue by keyunluo** [Haixing-Hu/nju-thesis#31]
在Ubuntu16.04系统中,  XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/Debian) (preloaded format=xelatex)生成的文档丢失标题序号:
![image](https://user-images.githubusercontent.com/18658607/49699054-232e2f00-fc07-11e8-9a7a-60cf80b5423e.png)
似乎\titleformat并没有工作。

**Comment by xspin** [comment]
把\titleformat后的[hang]选项改为[block]
