### ISSUE TITLE
公式字体问题

### ISSUE THREAD

**Issue by jiangqy** [Haixing-Hu/nju-thesis#39]
Hi, 

感谢分享。

请教下这个模板显示的公式字体似乎与直接用latex写的文档的字体稍有不同，请问如何显示成正常公式字体？

例如使用如下代码：
`
字体测试

\begin{itemize}
\item 英文小写字母：$x$
\item 英文黑体小写字母：${\bf x}$
\item 英文黑体小写斜体字母：${\boldsymbol x}$
\item 英文大写字母：$X$
\item 英文黑体大写字母：${\bf X}$
\item 英文黑体大写斜体字母：${\boldsymbol X}$
\end{itemize}
`

结果显示为：
<img width="321" alt="image" src="https://user-images.githubusercontent.com/14566109/75246061-f36a4780-5809-11ea-8735-66ca9dc48c44.png">

而正常显示为：
<img width="135" alt="image2" src="https://user-images.githubusercontent.com/14566109/75246195-3fb58780-580a-11ea-9778-2a7a5283023d.png">

其中最明显的，${\bf x}$是明显不一样的。

谢谢。

**Comment by zhy91** [comment]
公式环境中的黑体是否用 `\mathbf` 更好点？
另外，推荐使用 Unicode-math 宏包，我使用这个并用 `\newcommand` 来统一设置不同的格式，也可以自己安装并选定数学字体，感觉良好。

**Comment by jiangqy** [comment]
@zhy91 感谢回复，我发现`\mathbf`和`\bf`是差不多的，我尝试过Unicode-math 包，但是加入这个包就出bug了。您用这个宏包有遇到问题吗？

**Comment by jiangqy** [comment]
@zhy91 我已经解决了那个bug，但是使用unicode-math后设置没有用，能否share一下您定义的command?

**Comment by zhy91** [comment]
> @zhy91 我已经解决了那个bug，但是使用unicode-math后设置没有用，能否share一下您定义的command?

我目前在用的模板也参考了其他人基于此 repo 的模板，您可以搜索“nju thesis”查看，所以我的模板比较混乱，也不清楚 unicode-math 是否曾有冲突。下面是我在导言部分的一些设置，供您参考，请提前安装对应的数学字体。
```LaTex
\usepackage{unicode-math}
\unimathsetup{
  math-style  = ISO,
  bold-style  = ISO,
  nabla       = upright,
  partial     = upright,
}
\setmathfont{XITS Math}[StylisticSet=08] % upright integral symbols
```

**Comment by jiangqy** [comment]
@zhy91 感谢！我试了，还是不太work，不过我看了学长去年的论文，他们也没改，不打算折腾了。

ps, 我试了`\usepackage{mathpazo}`包，倒是会改成其他的字体，但是这个包感觉更不合适。

谢谢！

**Comment by jiangqy** [comment]
@zhy91 在另一repo里解决了。
https://github.com/njuHan/njuthesis-nju-thesis-template/issues/11
